// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa_y9_Y0RujGUOg4jx9uXJF0RLR_IkGZo',
    appId: '1:95440166212:web:3058168151ead10fb38b11',
    messagingSenderId: '95440166212',
    projectId: 'login-9cce1',
    authDomain: 'login-9cce1.firebaseapp.com',
    storageBucket: 'login-9cce1.appspot.com',
    measurementId: 'G-HYGQ03HQWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOuNKOKu72uyqeCbLzSTQ0t83NWd-Uf9A',
    appId: '1:95440166212:android:d786d6998e000fb5b38b11',
    messagingSenderId: '95440166212',
    projectId: 'login-9cce1',
    storageBucket: 'login-9cce1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HHsn3FDDr_TYkbgIbFp3ok1M3EQpipA',
    appId: '1:95440166212:ios:c187c72a2e646d56b38b11',
    messagingSenderId: '95440166212',
    projectId: 'login-9cce1',
    storageBucket: 'login-9cce1.appspot.com',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HHsn3FDDr_TYkbgIbFp3ok1M3EQpipA',
    appId: '1:95440166212:ios:c187c72a2e646d56b38b11',
    messagingSenderId: '95440166212',
    projectId: 'login-9cce1',
    storageBucket: 'login-9cce1.appspot.com',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa_y9_Y0RujGUOg4jx9uXJF0RLR_IkGZo',
    appId: '1:95440166212:web:6b6b38d6ca2b58a2b38b11',
    messagingSenderId: '95440166212',
    projectId: 'login-9cce1',
    authDomain: 'login-9cce1.firebaseapp.com',
    storageBucket: 'login-9cce1.appspot.com',
    measurementId: 'G-7795XR3X71',
  );

}